#!/usr/bin/env python3
"""
tools/fetch_fry.py
Generates tools/fry_words.txt — word frequency tiers used by generate_words.py
to classify antonym pairs as easy / medium / hard.

Uses the `wordfreq` library (backed by subtitle + web corpora).
Zipf score thresholds:
  easy   >= 5.8   very common everyday words
  medium >= 5.0   common but not basic
  hard    < 5.0   (not written to file; everything else is hard by default)

Whitelist words in generate_words.py always override to 'easy' regardless.

Usage:
  python tools/fetch_fry.py
"""
import sys
from pathlib import Path

TOOLS_DIR   = Path(__file__).parent
OUT_FILE    = TOOLS_DIR / 'fry_words.txt'
EASY_ZIPF   = 5.8
MEDIUM_ZIPF = 5.0


def install_and_import(package):
    try:
        return __import__(package)
    except ImportError:
        import subprocess
        print(f'Installing {package}...')
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', package])
        return __import__(package)


def get_wordnet():
    try:
        from nltk.corpus import wordnet as wn
        wn.synsets('test')
        return wn
    except LookupError:
        import nltk
        nltk.download('wordnet', quiet=True)
        nltk.download('omw-1.4', quiet=True)
        from nltk.corpus import wordnet as wn
        return wn


def main():
    wf_module = install_and_import('wordfreq')
    zipf_frequency = wf_module.zipf_frequency

    wn = get_wordnet()

    print('Collecting WordNet lemmas...')
    all_words = set()
    for synset in wn.all_synsets():
        for lemma in synset.lemmas():
            w = lemma.name().lower()
            if w.isalpha():
                all_words.add(w)

    print(f'  {len(all_words)} unique lemmas — scoring...')
    easy, medium = [], []
    for word in sorted(all_words):
        z = zipf_frequency(word, 'en')
        if z >= EASY_ZIPF:
            easy.append(word)
        elif z >= MEDIUM_ZIPF:
            medium.append(word)

    with open(OUT_FILE, 'w', encoding='utf-8') as f:
        f.write('# Word frequency tiers for difficulty classification\n')
        f.write(f'# easy:   zipf >= {EASY_ZIPF}  (~basic everyday vocabulary)\n')
        f.write(f'# medium: zipf >= {MEDIUM_ZIPF}  (~common but not basic)\n')
        f.write('# hard:   everything else (not listed — default in generate_words.py)\n')
        f.write('# Generated by tools/fetch_fry.py — re-run to refresh.\n\n')
        f.write('[easy]\n')
        for w in easy:
            f.write(w + '\n')
        f.write('\n[medium]\n')
        for w in medium:
            f.write(w + '\n')

    print(f'Done — {len(easy)} easy, {len(medium)} medium words → {OUT_FILE}')


if __name__ == '__main__':
    main()
